sylius_resource:
    resources:
        app.sponsor:
            classes:
                model: App\Entity\Sponsoring\Sponsor
                form: App\Form\Type\Resource\Sponsoring\SponsorType
            templates: '@SyliusAdmin/Crud'
        
        app.sponsor_logo:
            classes:
                model: App\Entity\Sponsoring\SponsorLogo
                form: App\Form\Type\Resource\Sponsoring\SponsorLogoType

sylius_grid:
    grids:
        app_admin_sponsor:
            driver:
                name: doctrine/orm
                options:
                    class: '%app.model.sponsor.class%'
            filters:
                code:
                    type: string
                    label: app.ui.code
                name:
                    type: string
                    label: app.ui.name
                tier:
                    type: select
                    label: app.ui.tier
                    form_options:
                        choices:
                            app.ui.sponsor_tier_host: Host
                            app.ui.sponsor_tier_regular: Regular
            fields:
                code:
                    type: string
                    label: app.ui.code
                    sortable: ~
                name:
                    type: string
                    label: app.ui.name
                    sortable: ~
                tier:
                    type: string
                    label: app.ui.tier
                    sortable: ~
            actions:
                main:
                    create:
                        type: create
                        label: sylius.ui.create
                item:
                    delete:
                        type: delete
                        label: sylius.ui.delete
                    update:
                        type: update
                        label: sylius.ui.update

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Form\Type\Resource\Sponsoring\SponsorType:
        arguments:
            - '%app.model.sponsor.class%'
            - ['sylius']
    
    App\Form\Type\Resource\Sponsoring\SponsorLogoType:
        arguments:
            - '%app.model.sponsor_logo.class%'
            - ['sylius']
    
    app.listener.sponsor_logo_upload_listener:
        class: Sylius\Bundle\CoreBundle\EventListener\ImageUploadListener
        tags:
            - { name: kernel.event_listener, event: app.sponsor.pre_create, method: uploadImage }
            - { name: kernel.event_listener, event: app.sponsor.pre_update, method: uploadImage }
